easychat:
  security:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}

spring:
  datasource:
    url: jdbc:postgresql://${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}+
  flyway:
    url: jdbc:postgresql://${BD_URL}
    user: ${BD_USERNAME}
    password: ${BD_PASSWORD}